package eredmel.regex;

import java.util.HashMap;
import java.util.Stack;

/**
 * The State of an Enregex matcher. This will contain all the open matched paren
 * assertions in existence.
 * 
 * @author Kavi Gupta
 *
 */
class EnregexSystem {
	/**
	 * A map mapping close parenthesis characters to the locations at which
	 * open assertions of matched parenthesis take place in the matcher string.
	 */
	private final HashMap<Integer, Stack<Integer>> openParenthesis;
	private final EnregexSegment matchingString;
	final EnregexType type;
	/**
	 * Creates an EnregexSystem with the given matching string suppplier and
	 * quote system.
	 */
	EnregexSystem(CharSequence text, EnregexType type) {
		this.openParenthesis = new HashMap<>();
		this.matchingString = EnregexSegment.getInstance(text, type);
		this.type = type;
	}
	/**
	 * Adds a parenthesis to the record, along with a location in the string
	 * for the parenthesis.
	 */
	void addParen(int paren, int location) {
		int close = type.matching(paren);
		if (!openParenthesis.containsKey(close))
			openParenthesis.put(close, new Stack<>());
		openParenthesis.get(close).push(location);
	}
	boolean parenMatches(int close, int location) {
		Stack<Integer> open = openParenthesis.get(close);
		if (open == null) return false;
		if (open.size() == 0) return false;
		return matchingString.parensMatch(open.pop(), location, close);
	}
	boolean quoteMatches(int openQuote, boolean positive, int loc) {
		if (positive)
			matchingString.quoteTypeMatches(loc, positive, openQuote);
		// TODO Autogenerated method stub
		return true;
	}
}
